
["Naga resurrection"]
	naga_trophy_block = "minecraft:wither_skeleton_skull"
	naga_ring_block = "twilightforest:ironwood_block"

["Lich resurrection"]
	lich_trophy_block = "minecraft:wither_skeleton_skull"
	lich_ring_block = "minecraft:gold_block"

["Hydra resurrection"]
	hydra_trophy_block = "minecraft:wither_skeleton_skull"
	hydra_ring_block = "minecraft:ancient_debris"

["Ur-Ghast resurrection"]
	urghast_trophy_block = "minecraft:wither_skeleton_skull"
	urghast_ring_block = "minecraft:crying_obsidian"

["Snow Queen resurrection"]
	sq_trophy_block = "minecraft:wither_skeleton_skull"
	sq_ring_block = "minecraft:lapis_block"

